version: "3.4"
services:
    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - '3306:3306'
      env_file:
        - docker.env
      volumes:
          - ${MYSQL_VOLUME:-./data/mysql}:/var/lib/mysql
    nginx:
        image: 'nginx:1.20'
        ports:
          - '80:80'
          - '443:443'
        restart: always
        volumes:
            - ${ROOT_DIR:-.}/:/var/www
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/ssl/localhost.crt:/etc/nginx/localhost.crt
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/ssl/localhost.key:/etc/nginx/localhost.key
    php-fpm:
        build:
          context: .
          dockerfile: ./docker-images/php-extended/Dockerfile
        image: "php-fpm"
        container_name: "php-fpm-rabbitmq"
        env_file:
          - docker.env
        restart: always
        volumes:
            - ${BUILD_CONTEXT:-.}/docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ${ROOT_DIR:-.}/:/var/www
        depends_on:
          - mysql
          - nginx
        command: [ "php-fpm" ]
    rabbitmq:
      image: 'rabbitmq:3.6-management'
      container_name: 'rabbitmq'
      ports:
        - '15672:15672'
        - '5672:5672'
      hostname: 'rabbitmq'
      env_file:
        - docker.env
      volumes:
          - ${BUILD_CONTEXT:-.}/docker-images/rabbitmq-extended/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
          - ${MYSQL_VOLUME:-./data/rabbitmq}:/var/lib/rabbitmq/mnesia/
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8090:80'
      env_file:
        - docker.env
    postgres:
      image: postgres
      container_name: "postgres-server"
      env_file:
        - docker.env
      volumes:
        - ./data/postgres:/var/lib/postgresql/data

    pg-adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080